In [54]:
import requests
import json
import pandas as pd

In [44]:
from datetime import datetime, timedelta

def date_range(start, end):
    start = datetime.strptime(start, "%Y-%m-%d")
    end = datetime.strptime(end, "%Y-%m-%d")
    dates = [(start + timedelta(days=i)).strftime("%Y-%m-%d") for i in range((end-start).days+1)]
    return dates

In [47]:
dates = date_range("2000-01-01", "2021-12-31")
dates = [date.replace('-', '') for date in dates]
dates

['20000101',
 '20000102',
 '20000103',
 '20000104',
 '20000105',
 '20000106',
 '20000107',
 '20000108',
 '20000109',
 '20000110',
 '20000111',
 '20000112',
 '20000113',
 '20000114',
 '20000115',
 '20000116',
 '20000117',
 '20000118',
 '20000119',
 '20000120',
 '20000121',
 '20000122',
 '20000123',
 '20000124',
 '20000125',
 '20000126',
 '20000127',
 '20000128',
 '20000129',
 '20000130',
 '20000131',
 '20000201',
 '20000202',
 '20000203',
 '20000204',
 '20000205',
 '20000206',
 '20000207',
 '20000208',
 '20000209',
 '20000210',
 '20000211',
 '20000212',
 '20000213',
 '20000214',
 '20000215',
 '20000216',
 '20000217',
 '20000218',
 '20000219',
 '20000220',
 '20000221',
 '20000222',
 '20000223',
 '20000224',
 '20000225',
 '20000226',
 '20000227',
 '20000228',
 '20000229',
 '20000301',
 '20000302',
 '20000303',
 '20000304',
 '20000305',
 '20000306',
 '20000307',
 '20000308',
 '20000309',
 '20000310',
 '20000311',
 '20000312',
 '20000313',
 '20000314',
 '20000315',
 '20000316',
 '20000317',
 '20000318',
 '20000319',
 '20000320',
 '20000321',
 '20000322',
 '20000323',
 '20000324',
 '20000325',
 '20000326',
 '20000327',
 '20000328',
 '20000329',
 '20000330',
 '20000331',
 '20000401',
 '20000402',
 '20000403',
 '20000404',
 '20000405',
 '20000406',
 '20000407',
 '20000408',
 '20000409',
 '20000410',
 '20000411',
 '20000412',
 '20000413',
 '20000414',
 '20000415',
 '20000416',
 '20000417',
 '20000418',
 '20000419',
 '20000420',
 '20000421',
 '20000422',
 '20000423',
 '20000424',
 '20000425',
 '20000426',
 '20000427',
 '20000428',
 '20000429',
 '20000430',
 '20000501',
 '20000502',
 '20000503',
 '20000504',
 '20000505',
 '20000506',
 '20000507',
 '20000508',
 '20000509',
 '20000510',
 '20000511',
 '20000512',
 '20000513',
 '20000514',
 '20000515',
 '20000516',
 '20000517',
 '20000518',
 '20000519',
 '20000520',
 '20000521',
 '20000522',
 '20000523',
 '20000524',
 '20000525',
 '20000526',
 '20000527',
 '20000528',
 '20000529',
 '20000530',
 '20000531',
 '20000601',
 '20000602',
 '20000603',
 '20000604',
 '20000605',
 '20000606',
 '20000607',
 '20000608',
 '20000609',
 '20000610',
 '20000611',
 '20000612',
 '20000613',
 '20000614',
 '20000615',
 '20000616',
 '20000617',
 '20000618',
 '20000619',
 '20000620',
 '20000621',
 '20000622',
 '20000623',
 '20000624',
 '20000625',
 '20000626',
 '20000627',
 '20000628',
 '20000629',
 '20000630',
 '20000701',
 '20000702',
 '20000703',
 '20000704',
 '20000705',
 '20000706',
 '20000707',
 '20000708',
 '20000709',
 '20000710',
 '20000711',
 '20000712',
 '20000713',
 '20000714',
 '20000715',
 '20000716',
 '20000717',
 '20000718',
 '20000719',
 '20000720',
 '20000721',
 '20000722',
 '20000723',
 '20000724',
 '20000725',
 '20000726',
 '20000727',
 '20000728',
 '20000729',
 '20000730',
 '20000731',
 '20000801',
 '20000802',
 '20000803',
 '20000804',
 '20000805',
 '20000806',
 '20000807',
 '20000808',
 '20000809',
 '20000810',
 '20000811',
 '20000812',
 '20000813',
 '20000814',
 '20000815',
 '20000816',
 '20000817',
 '20000818',
 '20000819',
 '20000820',
 '20000821',
 '20000822',
 '20000823',
 '20000824',
 '20000825',
 '20000826',
 '20000827',
 '20000828',
 '20000829',
 '20000830',
 '20000831',
 '20000901',
 '20000902',
 '20000903',
 '20000904',
 '20000905',
 '20000906',
 '20000907',
 '20000908',
 '20000909',
 '20000910',
 '20000911',
 '20000912',
 '20000913',
 '20000914',
 '20000915',
 '20000916',
 '20000917',
 '20000918',
 '20000919',
 '20000920',
 '20000921',
 '20000922',
 '20000923',
 '20000924',
 '20000925',
 '20000926',
 '20000927',
 '20000928',
 '20000929',
 '20000930',
 '20001001',
 '20001002',
 '20001003',
 '20001004',
 '20001005',
 '20001006',
 '20001007',
 '20001008',
 '20001009',
 '20001010',
 '20001011',
 '20001012',
 '20001013',
 '20001014',
 '20001015',
 '20001016',
 '20001017',
 '20001018',
 '20001019',
 '20001020',
 '20001021',
 '20001022',
 '20001023',
 '20001024',
 '20001025',
 '20001026',
 '20001027',
 '20001028',
 '20001029',
 '20001030',
 '20001031',
 '20001101',
 '20001102',
 '20001103',
 '20001104',
 '20001105',
 '20001106',
 '20001107',
 '20001108',
 '20001109',
 '20001110',
 '20001111',
 '20001112',
 '20001113',
 '20001114',
 '20001115',
 '20001116',
 '20001117',
 '20001118',
 '20001119',
 '20001120',
 '20001121',
 '20001122',
 '20001123',
 '20001124',
 '20001125',
 '20001126',
 '20001127',
 '20001128',
 '20001129',
 '20001130',
 '20001201',
 '20001202',
 '20001203',
 '20001204',
 '20001205',
 '20001206',
 '20001207',
 '20001208',
 '20001209',
 '20001210',
 '20001211',
 '20001212',
 '20001213',
 '20001214',
 '20001215',
 '20001216',
 '20001217',
 '20001218',
 '20001219',
 '20001220',
 '20001221',
 '20001222',
 '20001223',
 '20001224',
 '20001225',
 '20001226',
 '20001227',
 '20001228',
 '20001229',
 '20001230',
 '20001231',
 '20010101',
 '20010102',
 '20010103',
 '20010104',
 '20010105',
 '20010106',
 '20010107',
 '20010108',
 '20010109',
 '20010110',
 '20010111',
 '20010112',
 '20010113',
 '20010114',
 '20010115',
 '20010116',
 '20010117',
 '20010118',
 '20010119',
 '20010120',
 '20010121',
 '20010122',
 '20010123',
 '20010124',
 '20010125',
 '20010126',
 '20010127',
 '20010128',
 '20010129',
 '20010130',
 '20010131',
 '20010201',
 '20010202',
 '20010203',
 '20010204',
 '20010205',
 '20010206',
 '20010207',
 '20010208',
 '20010209',
 '20010210',
 '20010211',
 '20010212',
 '20010213',
 '20010214',
 '20010215',
 '20010216',
 '20010217',
 '20010218',
 '20010219',
 '20010220',
 '20010221',
 '20010222',
 '20010223',
 '20010224',
 '20010225',
 '20010226',
 '20010227',
 '20010228',
 '20010301',
 '20010302',
 '20010303',
 '20010304',
 '20010305',
 '20010306',
 '20010307',
 '20010308',
 '20010309',
 '20010310',
 '20010311',
 '20010312',
 '20010313',
 '20010314',
 '20010315',
 '20010316',
 '20010317',
 '20010318',
 '20010319',
 '20010320',
 '20010321',
 '20010322',
 '20010323',
 '20010324',
 '20010325',
 '20010326',
 '20010327',
 '20010328',
 '20010329',
 '20010330',
 '20010331',
 '20010401',
 '20010402',
 '20010403',
 '20010404',
 '20010405',
 '20010406',
 '20010407',
 '20010408',
 '20010409',
 '20010410',
 '20010411',
 '20010412',
 '20010413',
 '20010414',
 '20010415',
 '20010416',
 '20010417',
 '20010418',
 '20010419',
 '20010420',
 '20010421',
 '20010422',
 '20010423',
 '20010424',
 '20010425',
 '20010426',
 '20010427',
 '20010428',
 '20010429',
 '20010430',
 '20010501',
 '20010502',
 '20010503',
 '20010504',
 '20010505',
 '20010506',
 '20010507',
 '20010508',
 '20010509',
 '20010510',
 '20010511',
 '20010512',
 '20010513',
 '20010514',
 '20010515',
 '20010516',
 '20010517',
 '20010518',
 '20010519',
 '20010520',
 '20010521',
 '20010522',
 '20010523',
 '20010524',
 '20010525',
 '20010526',
 '20010527',
 '20010528',
 '20010529',
 '20010530',
 '20010531',
 '20010601',
 '20010602',
 '20010603',
 '20010604',
 '20010605',
 '20010606',
 '20010607',
 '20010608',
 '20010609',
 '20010610',
 '20010611',
 '20010612',
 '20010613',
 '20010614',
 '20010615',
 '20010616',
 '20010617',
 '20010618',
 '20010619',
 '20010620',
 '20010621',
 '20010622',
 '20010623',
 '20010624',
 '20010625',
 '20010626',
 '20010627',
 '20010628',
 '20010629',
 '20010630',
 '20010701',
 '20010702',
 '20010703',
 '20010704',
 '20010705',
 '20010706',
 '20010707',
 '20010708',
 '20010709',
 '20010710',
 '20010711',
 '20010712',
 '20010713',
 '20010714',
 '20010715',
 '20010716',
 '20010717',
 '20010718',
 '20010719',
 '20010720',
 '20010721',
 '20010722',
 '20010723',
 '20010724',
 '20010725',
 '20010726',
 '20010727',
 '20010728',
 '20010729',
 '20010730',
 '20010731',
 '20010801',
 '20010802',
 '20010803',
 '20010804',
 '20010805',
 '20010806',
 '20010807',
 '20010808',
 '20010809',
 '20010810',
 '20010811',
 '20010812',
 '20010813',
 '20010814',
 '20010815',
 '20010816',
 '20010817',
 '20010818',
 '20010819',
 '20010820',
 '20010821',
 '20010822',
 '20010823',
 '20010824',
 '20010825',
 '20010826',
 '20010827',
 '20010828',
 '20010829',
 '20010830',
 '20010831',
 '20010901',
 '20010902',
 '20010903',
 '20010904',
 '20010905',
 '20010906',
 '20010907',
 '20010908',
 '20010909',
 '20010910',
 '20010911',
 '20010912',
 '20010913',
 '20010914',
 '20010915',
 '20010916',
 '20010917',
 '20010918',
 '20010919',
 '20010920',
 '20010921',
 '20010922',
 '20010923',
 '20010924',
 '20010925',
 '20010926',
 '20010927',
 '20010928',
 '20010929',
 '20010930',
 '20011001',
 '20011002',
 '20011003',
 '20011004',
 '20011005',
 '20011006',
 '20011007',
 '20011008',
 '20011009',
 '20011010',
 '20011011',
 '20011012',
 '20011013',
 '20011014',
 '20011015',
 '20011016',
 '20011017',
 '20011018',
 '20011019',
 '20011020',
 '20011021',
 '20011022',
 '20011023',
 '20011024',
 '20011025',
 '20011026',
 '20011027',
 '20011028',
 '20011029',
 '20011030',
 '20011031',
 '20011101',
 '20011102',
 '20011103',
 '20011104',
 '20011105',
 '20011106',
 '20011107',
 '20011108',
 '20011109',
 '20011110',
 '20011111',
 '20011112',
 '20011113',
 '20011114',
 '20011115',
 '20011116',
 '20011117',
 '20011118',
 '20011119',
 '20011120',
 '20011121',
 '20011122',
 '20011123',
 '20011124',
 '20011125',
 '20011126',
 '20011127',
 '20011128',
 '20011129',
 '20011130',
 '20011201',
 '20011202',
 '20011203',
 '20011204',
 '20011205',
 '20011206',
 '20011207',
 '20011208',
 '20011209',
 '20011210',
 '20011211',
 '20011212',
 '20011213',
 '20011214',
 '20011215',
 '20011216',
 '20011217',
 '20011218',
 '20011219',
 '20011220',
 '20011221',
 '20011222',
 '20011223',
 '20011224',
 '20011225',
 '20011226',
 '20011227',
 '20011228',
 '20011229',
 '20011230',
 '20011231',
 '20020101',
 '20020102',
 '20020103',
 '20020104',
 '20020105',
 '20020106',
 '20020107',
 '20020108',
 '20020109',
 '20020110',
 '20020111',
 '20020112',
 '20020113',
 '20020114',
 '20020115',
 '20020116',
 '20020117',
 '20020118',
 '20020119',
 '20020120',
 '20020121',
 '20020122',
 '20020123',
 '20020124',
 '20020125',
 '20020126',
 '20020127',
 '20020128',
 '20020129',
 '20020130',
 '20020131',
 '20020201',
 '20020202',
 '20020203',
 '20020204',
 '20020205',
 '20020206',
 '20020207',
 '20020208',
 '20020209',
 '20020210',
 '20020211',
 '20020212',
 '20020213',
 '20020214',
 '20020215',
 '20020216',
 '20020217',
 '20020218',
 '20020219',
 '20020220',
 '20020221',
 '20020222',
 '20020223',
 '20020224',
 '20020225',
 '20020226',
 '20020227',
 '20020228',
 '20020301',
 '20020302',
 '20020303',
 '20020304',
 '20020305',
 '20020306',
 '20020307',
 '20020308',
 '20020309',
 '20020310',
 '20020311',
 '20020312',
 '20020313',
 '20020314',
 '20020315',
 '20020316',
 '20020317',
 '20020318',
 '20020319',
 '20020320',
 '20020321',
 '20020322',
 '20020323',
 '20020324',
 '20020325',
 '20020326',
 '20020327',
 '20020328',
 '20020329',
 '20020330',
 '20020331',
 '20020401',
 '20020402',
 '20020403',
 '20020404',
 '20020405',
 '20020406',
 '20020407',
 '20020408',
 '20020409',
 '20020410',
 '20020411',
 '20020412',
 '20020413',
 '20020414',
 '20020415',
 '20020416',
 '20020417',
 '20020418',
 '20020419',
 '20020420',
 '20020421',
 '20020422',
 '20020423',
 '20020424',
 '20020425',
 '20020426',
 '20020427',
 '20020428',
 '20020429',
 '20020430',
 '20020501',
 '20020502',
 '20020503',
 '20020504',
 '20020505',
 '20020506',
 '20020507',
 '20020508',
 '20020509',
 '20020510',
 '20020511',
 '20020512',
 '20020513',
 '20020514',
 '20020515',
 '20020516',
 '20020517',
 '20020518',
 '20020519',
 '20020520',
 '20020521',
 '20020522',
 '20020523',
 '20020524',
 '20020525',
 '20020526',
 '20020527',
 '20020528',
 '20020529',
 '20020530',
 '20020531',
 '20020601',
 '20020602',
 '20020603',
 '20020604',
 '20020605',
 '20020606',
 '20020607',
 '20020608',
 '20020609',
 '20020610',
 '20020611',
 '20020612',
 '20020613',
 '20020614',
 '20020615',
 '20020616',
 '20020617',
 '20020618',
 '20020619',
 '20020620',
 '20020621',
 '20020622',
 '20020623',
 '20020624',
 '20020625',
 '20020626',
 '20020627',
 '20020628',
 '20020629',
 '20020630',
 '20020701',
 '20020702',
 '20020703',
 '20020704',
 '20020705',
 '20020706',
 '20020707',
 '20020708',
 '20020709',
 '20020710',
 '20020711',
 '20020712',
 '20020713',
 '20020714',
 '20020715',
 '20020716',
 '20020717',
 '20020718',
 '20020719',
 '20020720',
 '20020721',
 '20020722',
 '20020723',
 '20020724',
 '20020725',
 '20020726',
 '20020727',
 '20020728',
 '20020729',
 '20020730',
 '20020731',
 '20020801',
 '20020802',
 '20020803',
 '20020804',
 '20020805',
 '20020806',
 '20020807',
 '20020808',
 '20020809',
 '20020810',
 '20020811',
 '20020812',
 '20020813',
 '20020814',
 '20020815',
 '20020816',
 '20020817',
 '20020818',
 '20020819',
 '20020820',
 '20020821',
 '20020822',
 '20020823',
 '20020824',
 '20020825',
 '20020826',
 '20020827',
 '20020828',
 '20020829',
 '20020830',
 '20020831',
 '20020901',
 '20020902',
 '20020903',
 '20020904',
 '20020905',
 '20020906',
 '20020907',
 '20020908',
 '20020909',
 '20020910',
 '20020911',
 '20020912',
 '20020913',
 '20020914',
 '20020915',
 '20020916',
 '20020917',
 '20020918',
 '20020919',
 '20020920',
 '20020921',
 '20020922',
 '20020923',
 '20020924',
 '20020925',
 '20020926',
 ...]

In [39]:
region = 108

In [53]:
for i in range(0, len(dates), 1000):
    print(dates[i])

20000101
20020927
20050623
20080319
20101214
20130909
20160605
20190302
20211126

In [34]:
url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList?serviceKey=x4FsKBVdvuLTh0q2A%2Fq%2Fzju25CkLxkAC2D4JrZJ8d7csnJsZ9fxhzfWpVIksPMT0flDjeu44GsCFvd4tF%2F5LWw%3D%3D&numOfRows=8036&pageNo=1&dataType=json&dataCd=ASOS&dateCd=DAY&startDt=20000101&endDt=20211231&stnIds=108'

In [35]:
contents = requests.get(url).text

In [36]:
data = json.loads(contents)

In [37]:
len(data['response']['body']['items']['item'])

100

In [38]:
data['response']['body']['items']['item'][-1]

{'stnId': '108',
 'stnNm': '서울',
 'tm': '2000-04-09',
 'avgTa': '11.8',
 'minTa': '5.9',
 'minTaHrmt': '0448',
 'maxTa': '19.2',
 'maxTaHrmt': '1621',
 'mi10MaxRn': '0.3',
 'mi10MaxRnHrmt': '2320',
 'hr1MaxRn': '1.0',
 'hr1MaxRnHrmt': '2310',
 'sumRnDur': '1.67',
 'sumRn': '0.8',
 'maxInsWs': '10.0',
 'maxInsWsWd': '250',
 'maxInsWsHrmt': '1703',
 'maxWs': '6.3',
 'maxWsWd': '230',
 'maxWsHrmt': '1720',
 'avgWs': '2.1',
 'hr24SumRws': '1851',
 'maxWd': '270',
 'avgTd': '0.4',
 'minRhm': '32',
 'minRhmHrmt': '1126',
 'avgRhm': '47.5',
 'avgPv': '6.5',
 'avgPa': '1005.3',
 'maxPs': '1021.8',
 'maxPsHrmt': '0252',
 'minPs': '1010.4',
 'minPsHrmt': '2400',
 'avgPs': '1015.8',
 'ssDur': '12.9',
 'sumSsHr': '4.0',
 'hr1MaxIcsrHrmt': '1500',
 'hr1MaxIcsr': '1.85',
 'sumGsr': '12.67',
 'ddMefs': '',
 'ddMefsHrmt': '',
 'ddMes': '',
 'ddMesHrmt': '',
 'sumDpthFhsc': '',
 'avgTca': '6.9',
 'avgLmac': '4.8',
 'avgTs': '14.1',
 'minTg': '0.5',
 'avgCm5Te': '12.0',
 'avgCm10Te': '12.0',
 'avgCm20Te': '11.5',
 'avgCm30Te': '11.0',
 'avgM05Te': '9.5',
 'avgM10Te': '8.7',
 'avgM15Te': '8.6',
 'avgM30Te': '10.0',
 'avgM50Te': '13.0',
 'sumLrgEv': '2.4',
 'sumSmlEv': '4.3',
 'n99Rn': '5.0',
 'iscs': '{박무}0130-{박무}{강도0}0300-{박무}{강도0}0600-0620.  {연무}1410-{연무}{강도0}1500-1745.  {비}2220-{비}{강도0}2400-',
 'sumFogDur': ''}

In [57]:
df = pd.read_csv('../mc_ha/data/20221214/최종_월별기상관측.csv', encoding='cp949')

In [60]:
df.head()

,Unnamed: 0,Unnamed: 0.1,지점,행정구역,지점명,일시,평균기온(°C),평균최고기온(°C),평균최저기온(°C),최고기온(°C),...,평균지면온도(°C),0.05m평균지중온도(°C),0.1m평균지중온도(°C),0.2m평균지중온도(°C),0.3m평균지중온도(°C),0.5m평균지중온도(°C),1.0m평균지중온도(°C),1.5m평균지중온도(°C),3.0m평균지중온도(°C),5.0m평균지중온도(°C)
0,0,0,90,강원도,속초,2000-01,-0.4,3.2,-4.0,9.9,...,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,90,강원도,속초,2000-02,-0.1,4.1,-4.4,9.2,...,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,90,강원도,속초,2000-03,6.9,11.5,2.1,18.5,...,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,90,강원도,속초,2000-04,11.2,16.0,6.5,24.1,...,13.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,90,강원도,속초,2000-05,14.3,18.8,10.7,30.5,...,17.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
import warnings
warnings.filterwarnings('ignore')
from tqdm import tqdm

In [65]:
df['합계 일사량(MJ/m2)'].isna().sum()

14328

In [70]:
df['합계 일사량(MJ/m2)'].median()

417.595

In [ ]:
train_x['enrolled_university'].fillna('no_enrollment')

In [66]:
len(df)

22846

In [69]:
region = df['행정구역'].unique()

In [85]:
new_df = pd.DataFrame()
for reg in tqdm(region):
    print(reg)
    reg_df = df[(df['행정구역'] == reg)]
    if reg_df['합계 일사량(MJ/m2)'].isna().sum() != len(reg_df):
        for si in reg_df['지점명'].unique():
            reg_df2 = reg_df[(reg_df['지점명'] == si)]
            for ym in reg_df2['일시'].unique():
                reg_df3 = reg_df2[(reg_df2['일시'] == ym)]
                reg_df3['합계 일사량(MJ/m2)'] = reg_df3['합계 일사량(MJ/m2)'].fillna(reg_df3['합계 일사량(MJ/m2)'].median())
                new_df = pd.concat([new_df, reg_df3], axis=0)
    else:
        print(f'모든 데이터가 결측치입니다. ---- {reg} count : {len(reg_df)}')

  0%|                                                                                                                                                                                   | 0/17 [00:00<?, ?it/s]

강원도

  6%|██████████                                                                                                                                                                 | 1/17 [00:04<01:12,  4.53s/it]

경기도

 12%|████████████████████                                                                                                                                                       | 2/17 [00:06<00:47,  3.19s/it]

인천광역시

 18%|██████████████████████████████▏                                                                                                                                            | 3/17 [00:08<00:33,  2.43s/it]

서울특별시

 24%|████████████████████████████████████████▏                                                                                                                                  | 4/17 [00:08<00:22,  1.71s/it]

경상북도

 29%|██████████████████████████████████████████████████▎                                                                                                                        | 5/17 [00:18<00:54,  4.50s/it]

충청북도

 35%|████████████████████████████████████████████████████████████▎                                                                                                              | 6/17 [00:22<00:49,  4.52s/it]

충청남도

 41%|██████████████████████████████████████████████████████████████████████▍                                                                                                    | 7/17 [00:28<00:48,  4.84s/it]

대전광역시

 47%|████████████████████████████████████████████████████████████████████████████████▍                                                                                          | 8/17 [00:29<00:32,  3.64s/it]

전라남도

 53%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                | 9/17 [00:44<00:57,  7.24s/it]

대구광역시

 59%|████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 10/17 [00:46<00:38,  5.48s/it]

전라북도

 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                            | 11/17 [00:57<00:43,  7.20s/it]

울산광역시
모든 데이터가 결측치입니다. ---- 울산광역시 count : 264
경상남도

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 13/17 [01:16<00:33,  8.34s/it]

광주광역시

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 14/17 [01:18<00:20,  6.70s/it]

부산광역시

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 15/17 [01:20<00:10,  5.39s/it]

제주도

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 16/17 [01:27<00:06,  6.07s/it]

세종특별자치시

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [01:28<00:00,  5.19s/it]

In [ ]:
new_df = pd.DataFrame()
for reg in tqdm(region):
    print(reg)
    reg_df = df[(df['행정구역'] == reg)]
    if reg_df['합계 일사량(MJ/m2)'].isna().sum() != len(reg_df):
        for si in reg_df['지점명'].unique():
            reg_df2 = reg_df[(reg_df['지점명'] == si)]
            for ym in reg_df2['일시'].unique():
                reg_df3 = reg_df2[(reg_df2['일시'] == ym)]
                reg_df3['합계 일사량(MJ/m2)'] = reg_df3['합계 일사량(MJ/m2)'].fillna(reg_df3['합계 일사량(MJ/m2)'].median())
                new_df = pd.concat([new_df, reg_df3], axis=0)
    else:
        print(f'모든 데이터가 결측치입니다. ---- {reg} count : {len(reg_df)}')

In [87]:
new_df['합계 일사량(MJ/m2)'].isna().sum()

14064

In [89]:
new_df.to_csv('../text.csv',index=False, encoding='utf-8-sig')

In [99]:
def get_median(data):
    data = sorted(data)
 
    centerIndex = len(data)//2
    return (data[centerIndex ] + data[-centerIndex - 1])/2

In [100]:
a = [1,2,3,4,6]

In [101]:
get_median(a)

3.0